from pydantic import BaseModel, Field
from typing import Optional

class PokemonSchema(BaseModel):
    national_number: int = Field(gt=0)
    gen: str = Field(min_length=1, max_length=4)
    pokemon_name: str = Field(min_length=1, max_length=50)
    primary_type: str = Field(min_length=1, max_length=50)
    secondary_type: Optional[str] = Field(max_length=50)
    classification: str = Field(min_length=1, max_length=50)
    height_m: float = Field(gt=0)
    weight_kg: float = Field(gt=0)
    hp: int = Field(gt=0)
    attack: int = Field(gt=0)
    defense: int = Field(gt=0)
    sp_attack: int = Field(gt=0)
    sp_defense: int = Field(gt=0)
    speed: int = Field(gt=0)
    abilities_0: str = Field(min_length=1, max_length=50)
    abilities_1: str = Field(min_length=1, max_length=50)
    is_sublegendary: bool = Field(default=False)
    is_legendary: bool = Field(default=False)
    is_mythical: bool = Field(default=False)
    evochain_1: str = Field(min_length=1, max_length=50)
    evochain_2: Optional[str] = Field(max_length=50)
    evochain_3: Optional[str] = Field(max_length=50)
    evochain_4: Optional[str] = Field(max_length=50)
    mega_evolution: Optional[str] = Field(max_length=50)
    description: str = Field(min_length=1, max_length=255)
    image: Optional[str] = Field(max_length=255)